Parameters:
  EventBusArn:
    Type: String
  EventBridgeRole:
    Type: String

Resources:
  EKSRule:
    Type: AWS::Events::Rule
    Properties: 
      Description: "Invoke CrowdStrike EKS Lambda when nodegroups or Fargate profiles are created."
      EventPattern: 
        source: 
          - "aws.eks"
        detail-type: 
          - "AWS API Call via CloudTrail"
        detail: 
          eventSource: 
            - "eks.amazonaws.com"
          eventName:
            - "CreateCluster"
            - "CreateFargateProfile"
      State: "ENABLED"
      Name: crowdstrike-eks-rule
      Targets: 
        - Arn: !Ref EventBusArn
          Id: "CrowdStrikeEKSFunction"
          RoleArn: !Ref EventBridgeRole