---
AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  EKSExecutionRoleName:
    Type: String
    Default: "crowdstrike-eks-execution-role"
  EventBridgeRoleName:
    Type: String
    Default: "crowdstrike-eks-eventbridge-role"
  EventBusAccount:
    Type: String
  EventBusName:
    Type: String
    Default: "crowdstrike-eks-eventbus"
  CodeBuildRoleName:
    Type: String
    Default: "crowdstrike-eks-codebuild-role"

Resources:
  EventBridgeRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: !Ref EventBridgeRoleName
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - events.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Policies:
        - PolicyName: crowdstrike-eks-eventbridge-policy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - events:PutEvents
                Resource:
                  - !Sub arn:${AWS::Partition}:events:${AWS::Region}:${EventBusAccount}:event-bus/${EventBusName}
  
  EKSExecutionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: !Ref EKSExecutionRoleName
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS: 
                - !Sub arn:${AWS::Partition}:iam::${EventBusAccount}:role/${EKSExecutionRoleName}
                - !Sub arn:${AWS::Partition}:sts::${EventBusAccount}:role/${CodeBuildRoleName}
            Action:
              - 'sts:AssumeRole'
      Policies:
        - PolicyName: crowdstrike-eks-execution-policy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: 
                  - eks:DescribeCluster
                  - eks:ListClusters
                  - eks:ListFargateProfiles
                  - ec2:DescribeRegions
                  - eks:UpdateClusterConfig
                  - eks:DescribeUpdate
                  - eks:AssociateAccessPolicy
                Resource: '*'
              - Effect: Allow
                Action: 
                  - ec2:DescribeRegions
                Resource: '*'
              - Effect: Allow
                Action:
                  - eks:UpdateAccessEntry
                  - eks:CreateAccessEntry
                  - eks:DeleteAccessEntry
                  - eks:DescribeAccessEntry
                Resource: 
                  - !Sub 'arn:${AWS::Partition}:eks:*:${AWS::AccountId}:cluster/*'
                  - !Sub 'arn:${AWS::Partition}:eks:*:${AWS::AccountId}:access-entry/*/${CodeBuildRoleName}/${EventBusAccount}/$/*'
