Parameters:
  EventBusArn:
    Type: String

Resources:
  EKSEventBridgeRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
        - Effect: Allow
          Principal:
            Service: events.amazonaws.com
          Action: sts:AssumeRole
      Policies:
      - PolicyName: crowdstrike-eks-eb-role
        PolicyDocument:
          Version: 2012-10-17
          Statement:
          - Effect: Allow
            Action: events:PutEvents
            Resource: !GetAtt EKSEventBus.Arn