---
AWSTemplateFormatVersion: '2010-09-09'
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Source S3 Bucket - Must be same Region as this stack
        Parameters:
          - EKSS3Bucket
      - Label:
          default: CrowdStrike Falcon Credentials
        Parameters:
          - FalconClientId
          - FalconClientSecret
          - FalconCID
          - CrowdStrikeCloud
          - DockerAPIToken
      - Label:
          default: Stackset Configuration
        Parameters:
          - Regions
          - ProvisionOU
      - Label:
          default: Event Configuration
        Parameters:
          - EventBusName
          - EventBridgeRoleName
      - Label:
          default: EKS Sensor Configuration
        Parameters:
          - Registry
          - Backend
          - EnableKAC
      - Label:
          default: CodeBuild Configuration
        Parameters:
          - CodeBuildProject
          - CodeBuildRole
          - KubernetesUserName

Parameters:
  EventBridgeRoleName: 
    Type: String
    Default: CrowdStrikeEKSProtectionRole
  EventBusName: 
    Type: String
    Default: CrowdStrikeEKSProtectionEventBus
  EKSS3Bucket:
    Type: String
    Default: paynecloud-org-bucket
  EnableEKS:
    Type: String
    Description: Enable CrowdStrike Automatic Sensor Deployment for EKS
    AllowedValues:
      - 'true'
      - 'false'
    Default: 'true'
  Backend:
    Type: String
    Description: kernel or bpf for Daemonset Sensor
    AllowedValues:
      - 'kernel'
      - 'bpf'
    Default: 'kernel'
  Registry:
    Type: String
    Description: Source Falcon Image from CrowdStrike or mirror to ECR
    AllowedValues:
      - 'crowdstrike'
      - 'ecr'
    Default: 'crowdstrike'
  EnableKAC:
    Type: String
    Description: Deploy Kubernetes Admission Controller (KAC).  For more info see https://falcon.crowdstrike.com/documentation/page/aa4fccee/container-security#s41cbec3
    AllowedValues:
      - 'true'
      - 'false'
    Default: 'true'
  CrowdStrikeCloud:
    Type: String
    Description: Cloud for your Falcon CID (eg. us-1, us-2 or eu-1)
    AllowedValues:
      - 'us-1'
      - 'us-2'
      - 'eu-1'
    Default: 'us-1'
  CodeBuildProject:
    Type: String
    Default: "crowdstrike-eks-codebuild"
  CodeBuildRole:
    Type: String
    Default: "crowdstrike-eks-codebuild-role"
  FalconClientId:
    Type: String
    NoEcho: true
    Default: ''
  FalconClientSecret:
    Type: String
    NoEcho: true
    Default: ''
  Regions:
    Type: CommaDelimitedList
    Default: ''
  ProvisionOU:
    Type: CommaDelimitedList
    Default: ''
  KubernetesUserName:
    Type: String
    Default: crowdstrike-eks
  FalconCID:
    Type: String
    Default: ''
  DockerAPIToken:
    Type: String
    NoEcho: true
    Default: ''

Conditions:
  UseECR: !Equals [ !Ref 'Registry', 'ecr' ]

Resources:
  EKSSetupStackSet:
    Type: AWS::CloudFormation::StackSet
    Properties:
      StackSetName: "CrowdStrike-EKS-SetUp-Stackset"
      Capabilities:
        - CAPABILITY_NAMED_IAM
      Parameters:
        - ParameterKey: EKSS3Bucket
          ParameterValue: !Ref EKSS3Bucket
        - ParameterKey: FalconClientId
          ParameterValue: !Ref FalconClientId
        - ParameterKey: FalconClientSecret
          ParameterValue: !Ref FalconClientSecret
        - ParameterKey: FalconCID
          ParameterValue: !Ref FalconCID
        - ParameterKey: CrowdStrikeCloud
          ParameterValue: !Ref CrowdStrikeCloud
        - ParameterKey: DockerAPIToken
          ParameterValue: !Ref DockerAPIToken
        - ParameterKey: Registry
          ParameterValue: !Ref Registry
        - ParameterKey: Backend
          ParameterValue: !Ref Backend
        - ParameterKey: EnableKAC
          ParameterValue: !Ref EnableKAC
        - ParameterKey: CodeBuildProject
          ParameterValue: !Ref CodeBuildProject
        - ParameterKey: CodeBuildRole
          ParameterValue: !Ref CodeBuildRole
        - ParameterKey: KubernetesUserName
          ParameterValue: !Ref KubernetesUserName
      PermissionModel: SERVICE_MANAGED
      AutoDeployment:
        Enabled: true
        RetainStacksOnAccountRemoval: true
      OperationPreferences:
        MaxConcurrentPercentage: 100
        FailureTolerancePercentage: 50
        RegionConcurrencyType: PARALLEL
      StackInstancesGroup:
        - DeploymentTargets:
            AccountFilterType: NONE
            OrganizationalUnitIds: !Ref ProvisionOU
          Regions:
            - !Ref AWS::Region
      TemplateURL: !Sub https://${EKSS3Bucket}.s3.${AWS::Region}.amazonaws.com/eks-protection-stackset.yml

  EKSEventBridgeStackSet:
    Type: AWS::CloudFormation::StackSet
    DependsOn:
      - EKSSetupStackSet
    Properties:
      StackSetName: "CrowdStrike-EKS-EB-Stackset"
      Parameters:
        - ParameterKey: EventBusName
          ParameterValue: !Ref EventBusName
        - ParameterKey: EventBusRegion
          ParameterValue: !Ref AWS::Region
        - ParameterKey: EventBridgeRoleName
          ParameterValue: !Ref EventBridgeRoleName
      PermissionModel: SERVICE_MANAGED
      AutoDeployment:
        Enabled: true
        RetainStacksOnAccountRemoval: true
      OperationPreferences:
        MaxConcurrentPercentage: 100
        FailureTolerancePercentage: 50
        RegionConcurrencyType: PARALLEL
      StackInstancesGroup:
        - DeploymentTargets:
            AccountFilterType: NONE
            OrganizationalUnitIds: !Ref ProvisionOU
          Regions: !Ref Regions
      TemplateURL: !Sub https://${EKSS3Bucket}.s3.${AWS::Region}.amazonaws.com/eks-eventbridge-stackset.yml
